name = "file-share-bot"
main = "src/index.js"
compatibility_date = "2024-07-12"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "users", id = "fill_id_here" },
  { binding = "msgs_keys", id = "fill_id_here" }
]
